/*******************************************************************************
* FILENAME: cyfitter_cfg.h
* PSoC Creator 2.0 Component Pack 3
*
* Description:
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright 2010-2011, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef CYFITTER_CFG_H
#define CYFITTER_CFG_H

#include <cytypes.h>

extern void cyfitter_cfg(void);

/* Analog Set/Unset methods */
extern void AnalogSetDefault(void);


#endif /* CYFITTER_CFG_H */

/*[]*/
