/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.0 Component Pack 3
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <USB_Bootloader.h>
#include <USB_Bootloader_audio.h>
#include <USB_Bootloader_cdc.h>
#include <USB_Bootloader_hid.h>
#include <USB_Bootloader_midi.h>
#include <emFile.h>
#include <USB_Bootloader_Dm_aliases.h>
#include <USB_Bootloader_Dp.h>
#include <USB_Bootloader_Dp_aliases.h>
#include <USB_Bootloader_ep8_dma.h>
#include <emFile_SPI0.h>
#include <emFile_mosi0.h>
#include <emFile_mosi0_aliases.h>
#include <emFile_Clock_1.h>
#include <emFile_miso0.h>
#include <emFile_miso0_aliases.h>
#include <emFile_sclk0.h>
#include <emFile_sclk0_aliases.h>
#include <emFile_SPI0_CS.h>
#include <emFile_SPI0_CS_aliases.h>
#include <cybtldr.h>
#include <cybtldr_common.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/
